### ISSUE TITLE
Adapting parsing to date format 

### ISSUE THREAD

**Issue by bepolymathe** [hkgnp/logseq-datenlp-plugin#2]
Hi, 

Date recognition is very useful for making references to days in the calendar but currently the inserted date does not respect the date format chosen by the user. 

![image](https://user-images.githubusercontent.com/29939805/150412128-adb8f500-664e-43e6-8fca-d947d96fc525.png)

Instead of `21-01-2022` ...
Here again the issue is the internationalization that your plugin calls for (IMHO).

**Comment by hkgnp** [comment]
Hmm, did you reload the plugin after change your date format?

**Comment by rosslaird** [comment]
I'm seeing something similar.
Scheduled date via regular `/Scheduled` method:
`SCHEDULED: <2022-01-21 Fri>`
Scheduled date shown by plugin with `/parse scheduled`:
`SCHEDULED: <2022-21-1 Friday>`
I have made no changes to my date format since I started using Logseq. So, it's the default.

**Comment by hkgnp** [comment]
@rosslaird Thanks! Your issue is different though as the SCHEDULED/DEADLINE function in Logseq is quite different in how they handle dates. What @bepolymathe is describing is the /parse dates function which does not need to rely on the SCHEDULED/ DEADLINE syntax.

Do you mind opening a new issue in Github, please? 

Thanks!

**Comment by rosslaird** [comment]
Sorry about that! It looked the same to me: inserted date different from user's date format.

**Comment by bepolymathe** [comment]
> Hmm, did you reload the plugin after change your date format?

Yes i have tried it. Nothing change.

**Comment by hkgnp** [comment]
Please update the plugin to the latest version 1.92 and let me know if the problem still persists?

You may need to restart Logseq to have the preferred user format take effect.

**Comment by ashishbhateja** [comment]
I have the same issue, currently using 2.1
My date settings are yyyy-MM-dd, and the plugin returns Jan 24th, 2022

**Comment by hkgnp** [comment]
Hmmm perhaps I think I'll added the preferred date format to settings first and call from there. 

Will update again.

**Comment by bepolymathe** [comment]
I just tried it with this version. I have again the problem of saving the settings. They are not taken into account after restarting logseq...

I try to change setting for `dd-MM-yyyy`

**Comment by hkgnp** [comment]
Could you copy and paste here what is in your settings file please?

**Comment by bepolymathe** [comment]
No problem. My settings... 

```
{
  "disabled": false,
  "preferredDateFormat": "dd-MM-yyyy",
  "lang": "fr"
}
```

**Comment by hkgnp** [comment]
Thanks!
And after restarting Logseq is it still the same? 

If so, can you screenshot what happens when you parse the date? 

If not, can you show what's different in the settings?

**Comment by bepolymathe** [comment]
Steps to reproduce: 
1. Change settings to :
```
{
  "disabled": false,
  "preferredDateFormat": "dd-MM-yyyy",
  "lang": "fr"
}
```
2. Save and restart logseq
3. Setting returns at previous state when logseq restart

```
{
  "disabled": false,
  "preferredDateFormat": "MMM do, yyyy",
  "lang": "fr"
}
```

**Comment by hkgnp** [comment]
And when you restart, your preferred date format for your journals are not
reset?

**Comment by bepolymathe** [comment]
> And when you restart, your preferred date format for your journals are not reset?

No

**Comment by bepolymathe** [comment]
As if there was a problem of right in writing... :thinking:

**Comment by hkgnp** [comment]
Hmm this is strange. I pick the preferred date format when the plugin loads
but yet it shows another date format.

I’m going to add a console log in the next version to see if there is any
discrepancy. If not, will need to file a bug report with Logseq.

**Comment by bepolymathe** [comment]
Ok. Let me know if you need more tests. Thanks for your effort

**Comment by hkgnp** [comment]
Hi! I've added a console log for the user's preferred date format. Could you update the App and let me know which preferred user format shows up in the console log?

Then perhaps restart Logseq and see what format comes up in the logs as well.

Thanks for your help!

**Comment by ashishbhateja** [comment]
the latest update seems to work fine for me 😃

**Comment by ituri** [comment]
In my config.edn I've set 
``` :journal/page-title-format "MMMM Do, yyyy"
 :journal/file-name-format "MMMM Do, yyyy"
 :date-formatter "MMMM Do, yyyy"```
and I've tried to set the same in the plugin's config, too:
```
{
  "disabled": false,
  "lang": "",
  "preferredDateFormat": "MMMM do, yyyy"
}
```
However, each time I restart the Logseq, the plugin's config resets itself to
```{
  "disabled": false,
  "lang": "",
  "preferredDateFormat": "MMM do, yyyy"
}
```
and `tomorrow`  is formatted as `date:: [[Jan 25th, 2022]]`. All this happens on the latest version (2.7).

**Comment by bepolymathe** [comment]
> let me know which preferred user format shows up in the console log?

How to show this ?

**Comment by bepolymathe** [comment]
Console returns 

```
module.js:215 Unexpected error when checking capturing opt-out status: TypeError: Cannot read properties of undefined (reading 'token')
(anonymous) @ module.js:215
(anonymous) @ posthog.cljs:52
$APP.$JSCompiler_prototypeAlias$$.$cljs$core$IFn$_invoke$arity$1$ @ core.cljs:11199
$switch__29647__auto__$jscomp$46$$ @ events.cljs:274
$frontend$handler$events$run_BANG__$_state_machine__29648__auto____1$$ @ events.cljs:274
$cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped$$ @ ioc_helpers.cljs:46
(anonymous) @ ioc_helpers.cljs:53
(anonymous) @ channels.cljs:61
$cljs$core$async$impl$dispatch$process_messages$$ @ dispatch.cljs:29
$channel$jscomp$1$$.port1.onmessage @ nexttick.js:208
block.cljs:373 page-inner's page-entity is nil, given page-name:  jan 25th, 2022  page-name-in-block:  Jan 25th, 2022
(anonymous) @ block.cljs:373
(anonymous) @ block.cljs:438
$cljs$core$apply_to_simple$cljs$0core$0IFn$0_invoke$0arity$06$$ @ core.cljs:3950
$cljs$core$apply_to_simple$cljs$0core$0IFn$0_invoke$0arity$05$$ @ core.cljs:3945
$cljs$core$apply_to_simple$cljs$0core$0IFn$0_invoke$0arity$04$$ @ core.cljs:3939
$cljs$core$apply_to_simple$cljs$0core$0IFn$0_invoke$0arity$03$$ @ core.cljs:3933
$APP.$cljs$core$apply$$.$cljs$core$IFn$_invoke$arity$2$ @ core.cljs:3962
$class$$jscomp$4$$ @ core.cljs:197
$f @ react-dom.production.min.js:158
Yq @ react-dom.production.min.js:268
Ni @ react-dom.production.min.js:251
oj @ react-dom.production.min.js:251
Jk @ react-dom.production.min.js:244
(anonymous) @ react-dom.production.min.js:124
t.unstable_runWithPriority @ scheduler.production.min.js:19
nf @ react-dom.production.min.js:123
Ph @ react-dom.production.min.js:124
Oh @ react-dom.production.min.js:123
wj @ react-dom.production.min.js:238
enqueueForceUpdate @ react-dom.production.min.js:135
l.forceUpdate @ react.production.min.js:13
(anonymous) @ core.cljs:376
(anonymous) @ cursor.cljs:29
$APP.$JSCompiler_prototypeAlias$$.$cljs$core$IWatchable$_notify_watches$arity$3$ @ core.cljs:4467
$APP.$cljs$core$reset_BANG_$$ @ core.cljs:4501
$APP.$cljs$core$swap_BANG_$$.$cljs$core$IFn$_invoke$arity$2$ @ core.cljs:4536
$APP.$frontend$state$set_editing_BANG_$cljs$0core$0IFn$0_invoke$0arity$05$$ @ state.cljs:896
$frontend$handler$editor$edit_block_BANG_$cljs$0core$0IFn$0_invoke$0arity$04$$ @ editor.cljs:233
$APP.$frontend$handler$editor$edit_block_BANG_$cljs$0core$0IFn$0_invoke$0arity$03$$ @ editor.cljs:226
(anonymous) @ api.cljs:442
k @ lsplugin.core.js:2
(anonymous) @ lsplugin.core.js:2
a.emit @ lsplugin.core.js:2
(anonymous) @ lsplugin.core.js:2
(anonymous) @ lsplugin.core.js:2
B.listener @ lsplugin.core.js:2
postMessage (async)
emit @ index.e72e0a77.js:2
_call @ index.e72e0a77.js:2
callAsync @ index.e72e0a77.js:2
(anonymous) @ index.e72e0a77.js:2
(anonymous) @ index.e72e0a77.js:22
async function (async)
(anonymous) @ index.e72e0a77.js:22
setTimeout (async)
v @ index.e72e0a77.js:22
async function (async)
v @ index.e72e0a77.js:22
(anonymous) @ index.e72e0a77.js:22
setTimeout (async)
(anonymous) @ index.e72e0a77.js:22
o.emit @ index.e72e0a77.js:2
#lspmsg# @ index.e72e0a77.js:2
(anonymous) @ index.e72e0a77.js:2
postMessage (async)
call @ lsplugin.core.js:2
_callUserModel @ lsplugin.core.js:2
callUserModel @ lsplugin.core.js:2
_hook @ lsplugin.core.js:2
hookEditor @ lsplugin.core.js:2
$cljs$core$js_invoke$$.$cljs$core$IFn$_invoke$arity$variadic$ @ core.cljs:534
$frontend$handler$plugin$hook_plugin$$ @ plugin.cljs:352
(anonymous) @ commands.cljs:498
$APP.$JSCompiler_prototypeAlias$$.$cljs$core$IFn$_invoke$arity$2$ @ core.cljs:11205
$frontend$commands$handle_steps$$ @ commands.cljs:683
$frontend$handler$editor$insert_command_BANG_$$ @ editor.cljs:1555
(anonymous) @ editor.cljs:35
$goog$events$KeyNames$$.8 @ config.cljs:22
$G__23090__1$$ @ core.cljs:4339
$f$jscomp$712$$ @ core.cljs:94
$JSCompiler_StaticMethods_fireListeners$$ @ eventtarget.js:341
$APP.$JSCompiler_prototypeAlias$$.dispatchEvent @ eventtarget.js:487
$APP.$JSCompiler_prototypeAlias$$.$handleKeyDown_$ @ keyboardshortcuthandler.js:1116
$APP.$JSCompiler_prototypeAlias$$.$handleBrowserKeyDown_$ @ keyboardshortcuthandler.js:1089
$goog$events$fireListener$$ @ events.js:837
$goog$events$handleBrowserEvent_$$ @ events.js:982
$f$jscomp$53$$ @ events.js:299
Show 6 more frames
```

**Comment by bepolymathe** [comment]
![image](https://user-images.githubusercontent.com/29939805/150796492-072fcdcf-232d-47c7-bd75-91941328c39c.png)

**Comment by bepolymathe** [comment]
![image](https://user-images.githubusercontent.com/29939805/150799287-7903a1cf-e4f4-4c4b-8e12-6631ba3ac2ac.png)

All logs are in the first post...

**Comment by hkgnp** [comment]
Hmm, logs pertaining to the plugin will begin with index(some number).js
though. These pertain to Logseq.

**Comment by ituri** [comment]
I'm getting this error when I'm parsing a date:
![Screenshot 2022-01-24 at 19 51 38](https://user-images.githubusercontent.com/871297/150845571-94d02811-737a-4008-a6ef-44aadac64cf8.png)

**Comment by ashishbhateja** [comment]
https://github.com/hkgnp/logseq-datenlp-plugin/issues/2#issuecomment-1019654980

Broken again in 2.7 :(

**Comment by hkgnp** [comment]
@ashishbhateja @ituri @bepolymathe 
I had some time to do a more detailed investigation. Interestingly, Logseq seems to always start with the default date format, then change it after it loads the user's settings.

I've set a delay to only catch the settings 3 seconds later, so hopefully it should work now. I'm so sorry for the frustration, I feel it too.

Please update to v2.8, and **restart Logseq**.

**Comment by ashishbhateja** [comment]
2.8 works fine for me. Thank you so much for finding a solution! I hope loges team can fix the issue with the default date format (I face a similar behavior when I use the iOS Logseq app. My journal pages open in the default date format and need a refresh before they reload correctly).
Incidentally, I discovered another bug where the date is not being correctly parsed. Please see the gif attached, hope it can explain the error
https://share.getcloudapp.com/2NuvPx5v

**Comment by hkgnp** [comment]
> 2.8 works fine for me. Thank you so much for finding a solution! I hope logseq team can fix the issue with the default date format (I face a similar behavior when I use the iOS Logseq app. My journal pages open in the default date format and need a refresh before they reload correctly).
> 
> Incidentally, I discovered another bug where the date is not being correctly parsed. Please see the gif attached, hope it can explain the error https://share.getcloudapp.com/2NuvPx5v

Glad it helps!

As for your screenshot, it's not really a bug but a limitation of the NLP library. You have a number in front of your date, so it throws the library off and interprets that as a date.

**Comment by ituri** [comment]
The problem continues to persist for me: The plugin still doesn't mind the date format supplied both by Logseq's config.edn as well as the plugins json-config.

**Comment by hkgnp** [comment]
Could you supply the dev logs again please?

**Comment by ituri** [comment]
![Screenshot 2022-01-25 at 16 18 11](https://user-images.githubusercontent.com/871297/151004608-6e36d983-1b68-48a5-8e2a-ccd845968f71.png)
This is the error I get when clicking update. Or is there anything else you want me to do when looking at the logs?

**Comment by hkgnp** [comment]
Is there a text in your dev console that says “Settings updated to
(preferred date format)”?

If not perhaps you can reinstall the plugin using the steps below.
1. Uninstall the Current one and close Logseq.
2. Go to .logseq/settings and delete logseq-datenlp-plugin.json
3. Open Logseq and install from marketplace.
4. Close Logseq.
5. Open Logseq and check dev console for the above.

**Comment by ituri** [comment]
I reproduced your steps and in the end I parsed the date for _tomorrow_. Again, it didn't apply my configuration (MMM instead of MMMM). Here's the log:
![Screenshot 2022-01-26 at 09 05 35](https://user-images.githubusercontent.com/871297/151125726-8e5c64b5-1126-4147-87a6-890f83646e36.png)

**Comment by hkgnp** [comment]
Sorry what is your configuration then?

**Comment by ituri** [comment]
Same as before: 
```{
  "disabled": false,
  "preferredDateFormat": "MMMM Do, yyyy",
  "lang": ""
}```

And also those entries in my `config.edn`:
```
 :journal/page-title-format "MMMM Do, yyyy"
 :journal/file-name-format "MMMM Do, yyyy"
 :date-formatter "MMMM Do, yyyy"
```

**Comment by hkgnp** [comment]
Oh! I think your date format is not supported. Only date formats with yyyy
or MM or did I think.

Will need to check.

**Comment by bepolymathe** [comment]
Sorry for my absence, I was overwhelmed. The problem persists for me also with the following configuration...

Version 2.5

```
{
  "disabled": false,
  "preferredDateFormat": "dd-MM-yyyy",
  "lang": "fr"
}
```

**Comment by hkgnp** [comment]
Could you share your console log?

**Comment by bepolymathe** [comment]
[logseq.log](https://github.com/hkgnp/logseq-datenlp-plugin/files/7942600/logseq.log)

**Comment by hkgnp** [comment]
Hmm, the start of the log should begin with an ASCII Logseq logo and a list of the plugins and then loading of the custom.css. Your logs didn't have those. Are you providing only a snapshot of the log?

**Comment by hkgnp** [comment]
> Same as before:
> 
> ```
> {
>   "disabled": false,
>   "preferredDateFormat": "MMMM Do, yyyy",
>   "lang": ""
> }
> ```
> 
> And also those entries in my `config.edn`:
> 
> ```
> :journal/page-title-format "MMMM Do, yyyy"
> :journal/file-name-format "MMMM Do, yyyy"
> :date-formatter "MMMM Do, yyyy"
> ```

Hi, I tried to add support for your date format in v2.91. Could you try to update using these steps:

1. Uninstall the Current one and close Logseq.
2. Go to .logseq/settings and delete logseq-datenlp-plugin.json
3. Open Logseq and install from marketplace.
4. Close Logseq.
5. Open Logseq and check dev console for the above.

**Comment by hkgnp** [comment]
> Same as before:
> 
> ```
> {
>   "disabled": false,
>   "preferredDateFormat": "MMMM Do, yyyy",
>   "lang": ""
> }
> ```

Hi, I tried adding support for your date format in v2.92. Please follow the steps below and see if it works?

1. Uninstall the Current one and close Logseq.
2. Go to .logseq/settings and delete logseq-datenlp-plugin.json
3. Open Logseq and install from marketplace.
4. Close Logseq.
5. Open Logseq and check dev console for the above.

**Comment by hkgnp** [comment]
> Sorry for my absence, I was overwhelmed. The problem persists for me also with the following configuration...
> 
> Version 2.5
> 
> ```
> {
>   "disabled": false,
>   "preferredDateFormat": "dd-MM-yyyy",
>   "lang": "fr"
> }
> ```

Hi, noted you are on v2.5 which doesn't account for the change I made here (https://github.com/hkgnp/logseq-datenlp-plugin/issues/2#issuecomment-1020813013). Please try the latest version 2.92 by following the steps below:

1. Uninstall the Current one and close Logseq.
2. Go to .logseq/settings and delete logseq-datenlp-plugin.json
3. Open Logseq and install from marketplace.
4. Close Logseq.
5. Open Logseq and check dev console for the above.

**Comment by ituri** [comment]
Still the same behaviour, even though I changed the plugin's config again after installing.
![Screenshot 2022-01-26 at 19 17 26](https://user-images.githubusercontent.com/871297/151222802-010162b3-d5d8-455f-8e63-242cc12a75b2.png)

**Comment by hkgnp** [comment]
It's interesting why your date settings is MMMM Do, yyyy but I don't have this option in my Logseq. Mine is MMMM do, yyyy with no capitalisation on "d". What does MMMM Do, yyyy look like in Logseq?

MMMM do, yyyy is `January 27th, 2022`.

What platform are you on?

**Comment by ituri** [comment]
Okay, I finally got it to work!😊 

Turns out that the capitalised d was indeed the problem!
I don't know how it got in there but it always worked as expected so I never saw any need to change it. Based on your comment, I changed it to lowercase and while it didn't affect logseq in any way, it eventually made your plugin work. Good work and thank you so much for your perseverance in solving this problem. 😊

**Comment by hkgnp** [comment]
Oh my goodness! Finally! It always turns out to be something that no one would have thought about! Glad that it finally did! Thanks for reporting this and persevering with me! 

Now all that's left is @bepolymathe. 😂

**Comment by bepolymathe** [comment]
> 2\. Go to .logseq/settings and delete logseq-datenlp-plugin.json

At this stage it's not working because after uninstallation I don't have this file anymore.

**Comment by bepolymathe** [comment]
If I continue and try to install the plugin again, it takes a long time...

![image](https://user-images.githubusercontent.com/29939805/151233576-17bc269c-989c-4b08-9512-01d8ae66f86a.png)

**Comment by bepolymathe** [comment]
> 5\. Open Logseq and check dev console for the above.

```

lsplugin.core.js:2 Object
core.cljs:41 
    Welcome to Logseq!
    If you encounter any problem, feel free to file an issue on GitHub (https://github.com/logseq/logseq)
    or join our Discord server (https://discord.gg/KpN4eHY).
    .____
    |    |    ____   ____  ______ ____  ______
    |    |   /  _ \ / ___\/  ___// __ \/ ____/
    |    |__(  <_> ) /_/  >___ \\  ___< <_|  |
    |_______ \____/\___  /____  >\___  >__   |
            \/    /_____/     \/     \/   |__|
     
index.abd4044c.js:1 [faiz:] === logseq-plugin-browser loaded ===
index.c4d7bc4f.js:72 Chart Render plugin loaded
index.b40d4ccf.js:1 #logseq-hypothesis: MAIN
index.25fdf9aa.js:2 [Inbox Telegram] Started!
index.25fdf9aa.js:2 [Inbox Telegram] Polling started!
index.a0b4e721.js:22 logseq-datenlp-plugin loaded
index.js:33 [faiz:] === markdown-table-editor-plugin loaded
index.2c3ccc6b.js:1 #doc loaded
index.fbccda4f.js:1 #logseq-heatmap: MAIN
index.fd2bfbd7.js:2 Table Render plugin loaded
index.824b7d0a.js:2 toc plugin loaded
index.421ac22b.js:2 logseq-maps-plugin loaded
index.81db35a5.js:2 Wordcount plugin loaded
index.1c518aa9.js:3 logseq-tweet-plugin loaded
core.cljs:193 "Datascript query: " [:find (pull ?b [:db/id :block/uuid :block/parent :block/left :block/collapsed? :block/format :block/refs :block/_refs :block/path-refs :block/tags :block/content :block/marker :block/priority :block/properties :block/pre-block? :block/scheduled :block/deadline :block/repeated? :block/created-at :block/updated-at :block/file :block/heading-level {:block/page [:db/id :block/name :block/original-name :block/journal-day]} {:block/_parent ...}]) :where [?b :block/refs [:block/name "card"]] nil]
core.cljs:193 "================"

core.cljs:193 "Use the following to debug your datalog queries:"

core.cljs:193 {:query
 [:find
  (pull
   ?b
   [:db/id
    :block/uuid
    :block/parent
    :block/left
    :block/collapsed?
    :block/format
    :block/refs
    :block/_refs
    :block/path-refs
    :block/tags
    :block/content
    :block/marker
    :block/priority
    :block/properties
    :block/pre-block?
    :block/scheduled
    :block/deadline
    :block/repeated?
    :block/created-at
    :block/updated-at
    :block/file
    :block/heading-level
    {:block/page
     [:db/id :block/name :block/original-name :block/journal-day]}
    {:block/_parent ...}])
  :where 
  [?b :block/refs [:block/name "card"]] 
  nil]}

core.cljs:193 "inputs (post-resolution):"

core.cljs:193 ()

core.cljs:193 "query-opts:"

core.cljs:193 {:use-cache? false, :disable-reactive? true}

index.9e6bc369.js:1 #tocgen loaded
core.cljs:193 "================"

core.cljs:193 "Use the following to debug your datalog queries:"

core.cljs:193 {:title "🟢 Tâches",
 :query
 [:find
  (pull ?block [*])
  :in
  $
  ?today
  :where
  [?block :block/marker ?marker]
  [(contains? #{"TODO"} ?marker)]
  (or [?block :block/scheduled ?d])
  [(<= ?d ?today)]], 
 :inputs [:today], 
 :collapsed? true}

core.cljs:193 "inputs (post-resolution):"

core.cljs:193 (20220126)

core.cljs:193 "query-opts:"

core.cljs:193 {}

core.cljs:193 "================"

core.cljs:193 "Use the following to debug your datalog queries:"

core.cljs:193 {:title "🔨 NOW",
 :query
 [:find
  (pull ?h [*])
  :in
  $
  ?start
  ?today
  :where
  [?h :block/marker ?marker]
  [(contains? #{"NOW" "DOING"} ?marker)]
  [?h :block/page ?p]
  [?p :block/journal? true]
  [?p :block/journal-day ?d]
  [(>= ?d ?start)]
  [(<= ?d ?today)]],
 :inputs [:14d :today],
 :result-transform
 (fn [result] (sort-by (fn [h] (get h :block/priority "Z")) result)),
 :collapsed? false}

core.cljs:193 "inputs (post-resolution):"

core.cljs:193 (20220112 20220126)

core.cljs:193 "query-opts:"

core.cljs:193 {}

core.cljs:193 "================"

core.cljs:193 "Use the following to debug your datalog queries:"

core.cljs:193 {:title "📅 NEXT",
 :query
 [:find
  (pull ?h [*])
  :in
  $
  ?start
  ?next
  :where
  [?h :block/marker ?marker]
  [(contains? #{"NOW" "LATER" "TODO"} ?marker)]
  [?h :block/ref-pages ?p]
  [?p :block/journal? true]
  [?p :block/journal-day ?d]
  [(> ?d ?start)]
  [(< ?d ?next)]],
 :inputs [:scheduled/future-days 7 :today :7d-after], 
 :collapsed? false}

core.cljs:193 "inputs (post-resolution):"

core.cljs:193 (:scheduled/future-days 7 20220126 20220202)

core.cljs:193 "query-opts:"

core.cljs:193 {}

core.cljs:193 "Custom query failed: "

core.cljs:193 {:query
 {:title "📅 NEXT",
  :query
  [:find
   (pull ?h [*])
   :in
   $
   ?start
   ?next
   :where
   [?h :block/marker ?marker]
   [(contains? #{"NOW" "LATER" "TODO"} ?marker)]
   [?h :block/ref-pages ?p]
   [?p :block/journal? true]
   [?p :block/journal-day ?d]
   [(> ?d ?start)]
   [(< ?d ?next)]],
  :inputs [:scheduled/future-days 7 :today :7d-after],
  :collapsed? false}}

query_react.cljs:120 $APP.$cljs$core$ExceptionInfo$$
core.cljs:193 reloading custom.css
DevTools failed to load source map: Could not parse content for file:///tmp/.mount_LogseqlmJq0M/resources/app/js/index.umd.js.map: Unexpected end of JSON input
core.cljs:193 reloading custom.css
index.a0b4e721.js:22 Settings updated to dd-MM-yyyy
DevTools failed to load source map: Could not parse content for file:///tmp/.mount_LogseqlmJq0M/resources/app/js/isomorphic-git/1.7.4/index.umd.min.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///tmp/.mount_LogseqlmJq0M/resources/app/js/index.umd.js.map: Unexpected end of JSON input
```

**Comment by bepolymathe** [comment]
I open the settings of the plugin and there ... miracle, it is the correct default date format that is recognized! A test with the command "parse date" and it works !

![image](https://user-images.githubusercontent.com/29939805/151237193-9c6fe761-6ddc-4489-8a25-8c0779efd1b3.png)

I think we are operational ! Thanks a lot !

**Comment by hkgnp** [comment]
Cool! So happy that it’s finally working!!!
